### ISSUE TITLE
Crash when pressing play

### ISSUE THREAD

**Issue by jcelerier** [pedromateo/openhmitester#4]
I get this stack trace, with Qt 5.5.0 on Linux

(gdb) bt
#0  0x00007ffff701e260 in QActionGroup::checkedAction() const () from /opt/Qt/5.5/gcc_64/lib/libQt5Widgets.so.5
#1  0x0000000000431e75 in HMITesterControl::tb_play_clicked (this=0x7fffffffe4f0) at ../hmi_tester/hmitestercontrol.cpp:212
#2  0x0000000000457f5c in HMITesterControl::qt_static_metacall (_o=0x7fffffffe4f0, _c=QMetaObject::InvokeMetaMethod, _id=8, _a=0x7fffffffd850) at moc_hmitestercontrol.cpp:204
#3  0x00007ffff55e636e in QMetaObject::activate(QObject*, int, int, void**) () from /opt/Qt/5.5/gcc_64/lib/libQt5Core.so.5
#4  0x00007ffff73adfc2 in QAbstractButton::clicked(bool) () from /opt/Qt/5.5/gcc_64/lib/libQt5Widgets.so.5
#5  0x00007ffff711e3f5 in ?? () from /opt/Qt/5.5/gcc_64/lib/libQt5Widgets.so.5
#6  0x00007ffff711ef89 in ?? () from /opt/Qt/5.5/gcc_64/lib/libQt5Widgets.so.5
#7  0x00007ffff711f124 in QAbstractButton::mouseReleaseEvent(QMouseEvent*) () from /opt/Qt/5.5/gcc_64/lib/libQt5Widgets.so.5
#8  0x00007ffff71df9fa in QToolButton::mouseReleaseEvent(QMouseEvent*) () from /opt/Qt/5.5/gcc_64/lib/libQt5Widgets.so.5
#9  0x00007ffff70650b8 in QWidget::event(QEvent*) () from /opt/Qt/5.5/gcc_64/lib/libQt5Widgets.so.5
#10 0x00007ffff71dfac9 in QToolButton::event(QEvent*) () from /opt/Qt/5.5/gcc_64/lib/libQt5Widgets.so.5
#11 0x00007ffff70244dc in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /opt/Qt/5.5/gcc_64/lib/libQt5Widgets.so.5
#12 0x00007ffff7029e25 in QApplication::notify(QObject*, QEvent*) () from /opt/Qt/5.5/gcc_64/lib/libQt5Widgets.so.5
#13 0x00007ffff55b86a3 in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /opt/Qt/5.5/gcc_64/lib/libQt5Core.so.5
#14 0x00007ffff7028ab2 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) () from /opt/Qt/5.5/gcc_64/lib/libQt5Widgets.so.5
#15 0x00007ffff707fe45 in ?? () from /opt/Qt/5.5/gcc_64/lib/libQt5Widgets.so.5
#16 0x00007ffff708217b in ?? () from /opt/Qt/5.5/gcc_64/lib/libQt5Widgets.so.5
#17 0x00007ffff70244dc in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /opt/Qt/5.5/gcc_64/lib/libQt5Widgets.so.5
#18 0x00007ffff7029640 in QApplication::notify(QObject*, QEvent*) () from /opt/Qt/5.5/gcc_64/lib/libQt5Widgets.so.5
#19 0x00007ffff55b86a3 in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /opt/Qt/5.5/gcc_64/lib/libQt5Core.so.5
#20 0x00007ffff67ab0ad in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () from /opt/Qt/5.5/gcc_64/lib/libQt5Gui.so.5
#21 0x00007ffff67aca85 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () from /opt/Qt/5.5/gcc_64/lib/libQt5Gui.so.5
#22 0x00007ffff6791c4f in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /opt/Qt/5.5/gcc_64/lib/libQt5Gui.so.5
#23 0x00007fffedd18170 in ?? () from /opt/Qt/5.5/gcc_64/plugins/platforms/../../lib/libQt5XcbQpa.so.5
#24 0x00007ffff3916fe7 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#25 0x00007ffff3917240 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#26 0x00007ffff39172ec in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#27 0x00007ffff560dae7 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /opt/Qt/5.5/gcc_64/lib/libQt5Core.so.5
#28 0x00007ffff55b6252 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /opt/Qt/5.5/gcc_64/lib/libQt5Core.so.5
#29 0x00007ffff55bdd3d in QCoreApplication::exec() () from /opt/Qt/5.5/gcc_64/lib/libQt5Core.so.5
#30 0x0000000000451973 in main (argc=1, argv=0x7fffffffe7c8) at main.cpp:46
(gdb)

**Comment by pedromateo** [comment]
Does it happen always, or after recording or playing something?

**Comment by pedromateo** [comment]
This error is weird, and cannot reproduce it :-(
It corresponds to this code snippet:

    //get the name of the selected testCase
    QAction *actionSelected = _playAndDeleteMenu_agroup->checkedAction();
    if ( !actionSelected )
    {
        QtUtils::newErrorDialog ( "There is not a selected Test Case." );
        return;
    }
